- name: play-1
  hosts: localhost
  tasks:
   - name: play-1 and task-1
     ansible.builtin.debug:
      msg: "Hi im learning devops from play-1 amd task-1"

- name: PLAY-2
  hosts: localhost
  tasks:
   - name:  PLAY-2 and TASK-2
     ansible.builtin.debug:
      msg: "hi im learning devops from PLAY-2 and TASK-2"