- name: variables
  hosts: localhost
  vars:
   course: devops
   trainer: sivakumar
   duration: 100hrs
  tasks: 
  - name: variable print information
    vars: 
     course: aws
    ansible.builtin.debug:
      msg: "hi im learing {{course}} from {{trainer}} ,duration is {{duration}}"
  - name: variable print information
    ansible.builtin.debug:
      msg: "hi im learing {{course}} from {{trainer}} ,duration is {{duration}}"