- name: vars from data-types
  hosts: localhost
  vars:
   course: Devops with aws #string
   Tools: #list
   - linux
   - ansible
   - terraform
   - kubernetes
   - jenkins
   Experience: #map or dictionary
    Devops: 3
    aws: 2
    terraform: 1
   Realproject: true #boolean
   tasks:
   - name: print vars
     ansible.builtin.debug:
      msg: "course is :{{course}},tools is :{{Tools}}, experience is :{{Experience}}, is realproject is:{{Realproject}}"
    