- name: conditions
  hosts: localhost
  tasks:
  - name: check user exists or not
    ansible.builtin.command: id expense
    register: user
    ignore_errors: true
  - name: print information
    ansible.builtin.debug:
     msg: "user info is : {{USER}}"
  - name: say hello
    ansible.builtin.debug:
     msg: "Hello"