- name: filters
  hosts: localhost
  tasks:
  - name: print info
    ansible.builtin.debug:
     msg: "Hello {{course | default ('Ansible')}}"
  
- name: upper case
  hosts: localhost
  vars_files:
  - vars.yaml
  tasks:
  - name:
    ansible.builtin.debug:
     msg: "{{greeting | upper}} "

- name: upper case
  hosts: localhost
  vars:
   greeting: hello good night
  tasks:
  - name:
    ansible.builtin.debug:
     msg: "{{greeting | upper}}"

- name: remove duplicates
  hosts: localhost
  vars:
   numbers: [ 1,2,3,3,1,5,6,7,8,7 ]
  tasks: 
  - name: remove duplicates
    ansible.builtin.debug:
     msg: "{{ numbers | unique }}"

- name: print min and max numbers
  hosts: localhost
  vars:
   num: [1,2,22,45,900]
  tasks:
  - name: print min number
    ansible.builtin.debug:
     msg: "{{ num | min }}"
  
  - name: print max number
    ansible.builtin.debug:
     msg: "{{ num | max }}"

- name: convert dictionary into list
  hosts: localhost
  vars:
   my_dict:
    course: ansible
    trainer: sivakumar
    duration: 100hrs
  tasks:
  - name: before conversion 
    ansible.builtin.debug:
     msg: "before conversion: {{ my_dict }}"

  - name: after conversion to list
    ansible.builtin.debug:
      msg: "after conversion: {{ my_dict | dict2items}}"
    
- name: convert items to dictionary
  hosts: localhost
  vars:
   my_list:
    - {'key': 'course', 'value': 'ansible'}
    - {'key': 'trainer', 'value': 'sivakumar'}
    - {'key': 'duration', 'value': '100hrs'}
  tasks:
  - name: convert items to dictonary
     ansible.builtin.debug:
      msg: " before conert : {{ my_list }}"

  - name: after conversion
     ansible.builtin.debug:
      msg: " after convert : {{ my_list | items2dict }}"