- name: filters
  hosts: localhost
  tasks:
  - name: print info
    ansible.builtin.debug:
     msg: "Hello {{course | default ('Ansible')}}"
  
- name: upper case
  hosts: localhost
  vars_files:
  - vars.yaml
  tasks:
  - name:
    ansible.builtin.debug:
     msg: "{{greeting | upper}} "

- name: upper case
  hosts: localhost
  vars:
   greeting: hello good night
  tasks:
  - name:
    ansible.builtin.debug:
     msg: "{{greeting | upper}}"
