- name: filters
  hosts: localhost
  tasks:
  - name: print info
    ansible.builtin.debug:
     msg: "Hello {{course | default ('Ansible')}}"
  
- name: upper case
  hosts: localhost
  vars_files:
  - vars.yaml
  tasks:
  - name:
    ansible.builtin.debug:
     msg: "{{greeting | upper}} "

- name: upper case
  hosts: localhost
  vars:
   greeting: hello good night
  tasks:
  - name:
    ansible.builtin.debug:
     msg: "{{greeting | upper}}"

- name: remove duplicates
  hosts: localhost
  vars:
   numbers: [1,2,3,3,1,5,6,7,8,7]
  tasks: 
  ansible.builtin.debug:
   msg: "{{ numbers | unique }}"
